[[ArcadeLearningEnvironment]]
arch = "aarch64"
git-tree-sha1 = "cd5760e8cbbbce0f681c8e162d104c8342b3d4a9"
os = "macos"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "8189f0eacadb17fbab299db58052dbf6c3a5d2c53aa6871b4880f71c071d2bda"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.aarch64-apple-darwin.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d49caa35d2ea875a43ea6cac0d1dc8c5cb646727"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "21b2edd1f5b553f7c7bc1c54e5343f20e667e595e13e5ddda9c5c5afc291d86d"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.aarch64-linux-gnu-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a9fa846fddf0c597eaa15432b8a72013e9a13c2"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "a36b3990a11b7fc07ccffb04ef3a558749b95033cf286fc6e403bc902f7a2d15"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.aarch64-linux-gnu-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4ccb3d98e886c16e18eea891e26193286e7fffc"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "38d5117017986ed3b826a7478ddc4215f00d221affa7774d22a62c466bc5e427"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.aarch64-linux-musl-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54227f4145af1f9735c94ece982eab5ede856bf6"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "377979a42b53916bf84cf3c6ef7907c93ecd905230b85b71fb8b79db3a89f7b7"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.aarch64-linux-musl-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8be648427d169c141ff66bd3cf7305e2b3b214d"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "e4d5f8c0c7715de610941723542373568fa071550768043582143be1a883c974"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed68cb571f36f4f55f17e54b2adc56834797fba3"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "cfd07cb922e8fa9e117990c215c5054c6e0b69cd15a88c02e7a9c8cedb342b5c"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c20caef988af3c865b32cd5a7ad22c4e42eea88"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "907b73b40d6b7791e7286a18eec673335a920346bc86105099b97b5c28988956"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae765326b8997c4d51dc9a0f7675d53ae973f9dd"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "deeb3c6d0e8539f47ac1b884ee251bd4e0c768c50a06c8c35e36652883dc9fb6"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ce5527f21a898f4e53c7d5bf38d87b8eb6d5c45"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "d601855f264017c57dd830efe993e0408bea32c4c1bcbb1a6b5f5a5f632ffa02"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea43de92bd53185065c6555e95651819177d7bca"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "88a82a43436ed54845139c104b0a37641e7f4f5e87c863ab0f240dbb6c1ce4dd"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e7ad2eb8cdff8a92a2339998b2c5bf84d76dfc6"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "1fc3f92f61ed91d5a16b817d4a486730109de7159b0118e126c1bfe3dddb2f83"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50fd66ce10983eb8e51b1c5997c4b9e79f5db0e5"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "280c303beb8f47c7d747c4743db2ecb4ba310e96f7a041bcf28782cd50dd0e02"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db993f7810e7f60722ce4269da705b993e917fde"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "0dab2c03fdd959f9bf45047862530eadddc91d7bd61830426d906374a695ced0"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.i686-linux-gnu-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8db352c6c3c6d8af91e1733c0ab70c13effa0089"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "8c1ab433abe88aa55577d2c9dc52ca6ac73cf4898b4395e717a2d2f959ea6cff"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.i686-linux-gnu-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3be1f0b70856534f93c266f89a5f59a58bb12adb"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "51b61f91368e141a395f57d661a928b31296b1b2bc15d8b22f2755caa687de24"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.i686-linux-musl-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53e723287b2fb104583547107de80682dd0465df"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "62bb9997f6cd45e886774f8189f08cb3f3369b4bfd9882f266cf10ed559aa1aa"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.i686-linux-musl-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "982043439a74e97d0d462275e1ad1903f39d86e5"
os = "windows"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "8ef5cab93333d77332fad7c84732f23afd26ad01843fd428c200c70bd7a26134"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.i686-w64-mingw32-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47895bbca78c8f6d375df25f0dd6de106368e990"
os = "windows"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "036cf9d6ed03ac8462bf1f5735f871546703de3fd3cbab32c6d7ccfa27e6ed8f"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.i686-w64-mingw32-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b70af0108b6eb1634a18f15f8bc8bf46c6e2e65"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "9e34204cd9a5fdb5ee46250d0858c8d2bf3d8aff961e81efde0af897ce4f2adb"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6636b8c8bb241883f0072bea037bd6a817ec8257"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "a185b0e7e5b3e2a4bdd26ca1126007ec9d997546ecfa36bface04295cbc707f4"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
git-tree-sha1 = "0a387d2816862320b4fda7cfcf863ed3e825e103"
os = "macos"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "8520200f93529021560c43b1a825e64d3fad8fcbef15b88424fe349cb474e07e"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-apple-darwin.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0e7b5b46fad5935f57e132bc760415cbb3bdc19"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "ff983bd8b78a72dce48eb3fffb5f49b4fcf6da16ce7e100b41d71073f3ce168f"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-linux-gnu-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6dbb39ee59c02a61d8a860d3ed7fb7875299408"
libc = "glibc"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "b2d8df32731dc6391f548132b1fa684b0b989b0cde1e1cc046eb9069dceb8139"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f02b9a8d77ce3f550ade81a80a839cd5584d2e10"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "548f0462f04c00d8fd037d16082aed687f6711a9cc14eacba04d713c5cb966fa"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-linux-musl-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0d63cdeb4f3bfda209b9653a875719d540e7ed6"
libc = "musl"
os = "linux"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "03cfbad78c517558c36a90397bc31f31c732f9e4dd2ef5eec841d929a20176d5"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-linux-musl-cxx11.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
git-tree-sha1 = "f002a501efb34f2118da29001a2007a62c73b7cb"
os = "freebsd"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "972ee86bb2a2c8b8fee498066171a6537462a0194745899bae1bd51d8b75520b"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-unknown-freebsd.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cb8367848b4d09d8bf61d9904cac10ac1be7ea9"
os = "windows"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "81d71979bebd3dff76caed7505f401f94ecaa52b513aabcaee3628f2a9d0a738"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[ArcadeLearningEnvironment]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed8105bb0397021386038f8c52bd4a7491a20552"
os = "windows"

    [[ArcadeLearningEnvironment.download]]
    sha256 = "d5357077a8d46671065721637643f0973bec7570df0d1410280aa3f2d6eb2af7"
    url = "https://github.com/JuliaBinaryWrappers/ArcadeLearningEnvironment_jll.jl/releases/download/ArcadeLearningEnvironment-v0.6.2+0/ArcadeLearningEnvironment.v0.6.2.x86_64-w64-mingw32-cxx11.tar.gz"
