# Autogenerated wrapper script for ArcadeLearningEnvironment_jll for aarch64-apple-darwin
export libale_c

using Zlib_jll
JLLWrappers.@generate_wrapper_header("ArcadeLearningEnvironment")
JLLWrappers.@declare_library_product(libale_c, "@rpath/libale_c.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libale_c,
        "lib/libale_c.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
