# Autogenerated wrapper script for ArcadeLearningEnvironment_jll for armv7l-linux-musleabihf-cxx11
export libale_c

using Zlib_jll
JLLWrappers.@generate_wrapper_header("ArcadeLearningEnvironment")
JLLWrappers.@declare_library_product(libale_c, "libale_c.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libale_c,
        "lib/libale_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
