# Autogenerated wrapper script for ArcadeLearningEnvironment_jll for i686-w64-mingw32-cxx03
export libale_c

using Zlib_jll
JLLWrappers.@generate_wrapper_header("ArcadeLearningEnvironment")
JLLWrappers.@declare_library_product(libale_c, "libale_c.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libale_c,
        "bin\\libale_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
